version: "3"
networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.30.0.0/24

services:
  api:
    build: ./restapi
    container_name: "restapi"
    ports:
      - "8080:8080"
    tty: true
    networks:
      app_net:
        ipv4_address: 172.30.0.20
    volumes:
      #
      # ローカルとコンテナのディレクトリをバインドマウント（同期）
      # これを指定しておかないと air でホットリロードが有効にならない
      - ./restapi/api:/api 
      #
      # パッケージやバイナリファイルのインストール先（$GOPATH）を永続化
      - go_path:/go

  app:
    build: ./webapp
    container_name: "webapp"
    ports:
      - "3000:3000"
    environment:
      TZ: "Asia/Tokyo"
    networks:
      app_net:
        ipv4_address: 172.30.0.30

volumes:
  go_path:

 
