version: "3"
services:
  api:
    build: ./restapi
    container_name: "restapi"
    ports:
      - "8080:8080"
    tty: true
  app:
    build: ./webapp
    container_name: "webapp"
    ports:
      - "8888:8888"
    environment:
      TZ: "Asia/Tokyo"
 
