version: "3"

networks:
  app-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.10.0/24

services:
  api:
    build: ./restapi
    container_name: "restapi"
    ports:
      - "8080:8080"
    tty: true
    networks:
      app-net:
        ipv4_address: 172.30.10.20
    volumes:
      #
      # ローカルとコンテナのディレクトリをバインドマウント（同期）
      # これを指定しておかないと air でホットリロードが有効にならない
      - ./restapi/api:/api 
      #
      # パッケージやバイナリファイルのインストール先（$GOPATH）を永続化
      - go_path:/go

  mysql:
    build: ./storage/
    container_name: "storage"
    volumes:
      - ./storage/init:/docker-entrypoint-initdb.d # 初期データ投入
    environment:
      MYSQL_ROOT_PASSWORD: mysqladmin
      MYSQL_DATABASE: mydb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysqladmin
      TZ: "Asia/Tokyo"
    hostname: storage
    restart: always
    ports:
      - 3306:3306
    networks: 
      app-net:
        ipv4_address: 172.30.10.100

  app:
    build: ./webapp
    container_name: "webapp"
    ports:
      - "3000:3000"
    environment:
      TZ: "Asia/Tokyo"
    networks:
      app-net:
        ipv4_address: 172.30.10.30

volumes:
  go_path:

 
